
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/clang64/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 6.2.9200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/msys64/clang64/share/cmake/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:5 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/msys64/clang64/bin/"
      - "C:/msys64/usr/local/bin/"
      - "C:/msys64/usr/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/msys64/usr/bin/site_perl/"
      - "C:/msys64/usr/bin/vendor_perl/"
      - "C:/msys64/usr/bin/core_perl/"
    searched_directories:
      - "C:/msys64/clang64/bin/ninja-build.com"
      - "C:/msys64/clang64/bin/ninja-build.exe"
      - "C:/msys64/clang64/bin/ninja-build"
      - "C:/msys64/clang64/bin/ninja.com"
    found: "C:/msys64/clang64/bin/ninja.exe"
    search_context:
      ENV{PATH}:
        - "C:\\msys64\\clang64\\bin"
        - "C:\\msys64\\usr\\local\\bin"
        - "C:\\msys64\\usr\\bin"
        - "C:\\msys64\\usr\\bin"
        - "C:\\Windows\\System32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\msys64\\usr\\bin\\site_perl"
        - "C:\\msys64\\usr\\bin\\vendor_perl"
        - "C:\\msys64\\usr\\bin\\core_perl"
  -
    kind: "find-v1"
    backtrace:
      - "C:/msys64/clang64/share/cmake/Modules/CMakeDetermineCompiler.cmake:63 (find_program)"
      - "C:/msys64/clang64/share/cmake/Modules/CMakeDetermineCCompiler.cmake:64 (_cmake_find_compiler)"
      - "CMakeLists.txt:5 (project)"
    mode: "program"
    variable: "CMAKE_C_COMPILER"
    description: "C compiler"
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: false
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: false
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: false
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "cc"
      - "gcc"
      - "cl"
      - "bcc"
      - "xlc"
      - "icx"
      - "clang"
    candidate_directories:
      - "C:/msys64/clang64/bin/"
      - "C:/msys64/usr/local/bin/"
      - "C:/msys64/usr/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/msys64/usr/bin/site_perl/"
      - "C:/msys64/usr/bin/vendor_perl/"
      - "C:/msys64/usr/bin/core_perl/"
    searched_directories:
      - "C:/msys64/clang64/bin/cc.com"
    found: "C:/msys64/clang64/bin/cc.exe"
    search_context:
      ENV{PATH}:
        - "C:\\msys64\\clang64\\bin"
        - "C:\\msys64\\usr\\local\\bin"
        - "C:\\msys64\\usr\\bin"
        - "C:\\msys64\\usr\\bin"
        - "C:\\Windows\\System32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\msys64\\usr\\bin\\site_perl"
        - "C:\\msys64\\usr\\bin\\vendor_perl"
        - "C:\\msys64\\usr\\bin\\core_perl"
  -
    kind: "find-v1"
    backtrace:
      - "C:/msys64/clang64/share/cmake/Modules/CMakeDetermineCompilerId.cmake:462 (find_file)"
      - "C:/msys64/clang64/share/cmake/Modules/CMakeDetermineCompilerId.cmake:500 (CMAKE_DETERMINE_COMPILER_ID_WRITE)"
      - "C:/msys64/clang64/share/cmake/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)"
      - "C:/msys64/clang64/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/msys64/clang64/share/cmake/Modules/CMakeDetermineCCompiler.cmake:122 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    mode: "file"
    variable: "src_in"
    description: "Path to a file."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "CMakeCCompilerId.c.in"
    candidate_directories:
      - "C:/msys64/clang64/share/cmake/Modules/"
    found: "C:/msys64/clang64/share/cmake/Modules/CMakeCCompilerId.c.in"
    search_context:
      ENV{PATH}:
        - "C:\\msys64\\clang64\\bin"
        - "C:\\msys64\\usr\\local\\bin"
        - "C:\\msys64\\usr\\bin"
        - "C:\\msys64\\usr\\bin"
        - "C:\\Windows\\System32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\msys64\\usr\\bin\\site_perl"
        - "C:\\msys64\\usr\\bin\\vendor_perl"
        - "C:\\msys64\\usr\\bin\\core_perl"
